version: "3.9"

services:
  web:
    build:
      context: ../
      dockerfile: ./docker/dockerfile.dev
    volumes:
      - ../:/app
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ENV=development
    depends_on:
      - db

  db:
    image: mysql:8.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"  
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: