# Build stage
FROM golang:1.24.1 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o cocite ./cmd/server

# Run stage
FROM debian:bookworm-slim

WORKDIR /app

COPY --from=builder /app/cocite .
COPY internal/templates/ internal/templates/

EXPOSE 80

CMD ["./cocite"]