FROM golang:1.24

WORKDIR /app

# Copy go.mod and download deps
COPY go.mod ./
RUN go mod download

# Copy the rest of the code
COPY . .

# Install any dev tools if you want
RUN apt-get update && apt-get install -y vim curl && rm -rf /var/lib/apt/lists/*
RUN go install github.com/air-verse/air@latest

EXPOSE 8080
EXPOSE 8081

# Run in dev mode
# CMD ["go", "run", "/app/cmd/server/main.go"]
CMD ["air"]